environment: "prod"
serviceAccountName: cwb07-sa
createIngress: false

net:
  host: "api.cwb07.dsgov.demo.nuvalence.io"

env:
  ALLOWED_ORIGINS: "http://localhost:4200, http://localhost:4201, https://api.cwb07.dsgov.demo.nuvalence.io, https://agency.cwb07.dsgov.demo.nuvalence.io, https://public.cwb07.dsgov.demo.nuvalence.io, https://employer.cwb07.dsgov.demo.nuvalence.io"
  CERBOS_URI: "127.0.0.1:3592"
  DB_CONNECTION_URL: "jdbc:postgresql://127.0.0.1:5432/cwb07-prod-audit-service-db"
  DB_USERNAME: "${sm://projects/cwb07-prod-b74b/secrets/cwb07-prod-db-user/versions/latest}"
  DB_PASSWORD: "${sm://projects/cwb07-prod-b74b/secrets/cwb07-prod-db-pass/versions/latest}"
  GCP_PROJECT_ID: "cwb07-prod-b74b"
  SELF_SIGN_PUBLIC_KEY: "${sm://projects/cwb07-prod-b74b/secrets/cwb07-self-signed-token-public-key/versions/latest}"
  SELF_SIGN_PRIVATE_KEY: "${sm://projects/cwb07-prod-b74b/secrets/cwb07-self-signed-token-private-key/versions/latest}"
  PUB_SUB_TOPIC: "AUDIT_EVENTS"
  PUB_SUB_TOPIC_SUBSCRIPTION: "AUDIT_EVENTS_SUBSCRIPTION"
  TOKEN_PRIVATE_KEY_SECRET: "cwb07-self-signed-token-private-key"
  TOKEN_ISSUER: "cwb07"
  TOKEN_PRIVATE_KEY_VERSION: "latest"
  OTEL_SAMPLER_PROBABILITY: 1.0 # valid values: [0.0 - 1.0]
  PUBSUB_EMULATOR_HOST: false # set actual "host:port" to enable or false to disable
  PUBSUB_EMULATOR_ENABLED: false # set to true to enable emulator
  # subscriptions separated by comma
  PUBSUB_SUBSCRIPTIONS: "projects/cwb07-prod-b74b/subscriptions/AUDIT_EVENTS_RECORDING_SUBSCRIPTION"
  # cwb07-events publisher topics separated by comma
  SUBSCRIBER_TOPICS: "AUDIT_EVENTS_RECORDING"
  PUBLISHER_TOPICS: projects/cwb07-prod-b74b/topics/APPLICATION_ROLE_REPORTING,projects/cwb07-prod-b74b/topics/AUDIT_EVENTS_RECORDING
